import fs from "node:fs";import crypto from "node:crypto";import {execFileSync} from "node:child_process";
const version=String(process.env.RELEASE_VERSION||process.env.GITHUB_REF_NAME||"").replace(/^v/,"");if(!/^\d+\.\d+\.\d+(?:[-+][0-9A-Za-z.-]+)?$/.test(version))throw new Error("RELEASE_VERSION must be semver");
const channel=process.env.RELEASE_CHANNEL||"stable";const apiBase=(process.env.MATEO_API_BASE_URL||"").replace(/\/$/,"");const publishToken=process.env.MATEO_RELEASE_PUBLISH_TOKEN;const supabaseUrl=(process.env.SUPABASE_URL||"").replace(/\/$/,"");const serviceKey=process.env.SUPABASE_SERVICE_ROLE_KEY;const privateKey=process.env.MATEO_ED25519_PRIVATE_KEY;const publicKey=process.env.MATEO_ED25519_PUBLIC_KEY;const keyId=process.env.MATEO_ED25519_KEY_ID||"mateo-ed25519-2026";
if(!apiBase||!publishToken||!supabaseUrl||!serviceKey||!privateKey||!publicKey)throw new Error("Missing release publishing secret(s).");
const sourceRepo=process.env.GITHUB_SYNC_REPO||"g13065994/MATEO-FMB";
const sourceCommit=execFileSync("git",["rev-parse","HEAD"],{encoding:"utf8"}).trim();
let baseCommit=process.env.GITHUB_SYNC_BASE_REF||"";
if(!baseCommit){try{baseCommit=execFileSync("git",["describe","--tags","--abbrev=0","HEAD^"],{encoding:"utf8"}).trim()}catch{try{baseCommit=execFileSync("git",["rev-parse","HEAD^"],{encoding:"utf8"}).trim()}catch{baseCommit=sourceCommit}}}
const protectedSyncPaths=[/^\\.env(?:\\.|$)/,/^data\\//,/^storage\\//,/^credentials\\//,/^config(?:\\/|\\.)/i,/^src\\/cmds\\//,/^src\\/events\\//,/^plugins\\//,/^node_modules\\//];
function syncablePath(p){return !protectedSyncPaths.some(r=>r.test(p))}
function changedFiles(){const raw=execFileSync("git",["diff","--name-status","--find-renames",baseCommit,sourceCommit],{encoding:"utf8"});return raw.split("\n").filter(Boolean).map(line=>{const parts=line.split("\t"),status=parts[0]||"M",path=status.startsWith("R")?parts[2]:parts[1];return{path,status:status.startsWith("A")?"added":status.startsWith("D")?"deleted":status.startsWith("R")?"renamed":"modified",previousPath:status.startsWith("R")?parts[1]:null,syncable:syncablePath(path)}})}
const githubSync={sourceRepo,sourceCommit,baseCommit,changedFiles:changedFiles()};\nconst out="mateo-fmb-"+version+".tar.gz";execFileSync("git",["archive","--format=tar.gz","--output",out,"HEAD"],{stdio:"inherit"});const bytes=fs.readFileSync(out);const sha256=crypto.createHash("sha256").update(bytes).digest("hex");const storageKey="fmb/"+version+"/"+sha256+".tar.gz";const upload=await fetch(supabaseUrl+"/storage/v1/object/mateo-releases/"+storageKey,{method:"POST",headers:{Authorization:"Bearer "+serviceKey,apikey:serviceKey,"Content-Type":"application/gzip","x-upsert":"false"},body:bytes});if(!upload.ok)throw new Error("Storage upload failed: "+await upload.text());
const manifest={schemaVersion:1,product:"fmb",apiVersion:"v1",version,channel,createdAt:new Date().toISOString(),artifact:{storageKey,sha256,sizeBytes:bytes.length,contentType:"application/gzip"},requirements:{node:">=22",os:["linux","darwin","win32"],arch:["x64","arm64"],adapter:"eryxenx-fca",database:"sqlite",writable:true,longRunning:true},support:{minimumNode:"22",apiVersion:"v1"},githubSync};
const payload=JSON.stringify(manifest);const manifestSha256=crypto.createHash("sha256").update(payload).digest("hex");const signature=crypto.sign(null,Buffer.from(payload),crypto.createPrivateKey(privateKey)).toString("base64url");
const body={version,channel,status:channel==="stable"?"stable":channel==="beta"?"beta":"testing",previousVersion:process.env.PREVIOUS_VERSION||null,changelog:process.env.RELEASE_CHANGELOG||"",manifest,manifestSha256,artifact:{storageKey,sha256,sizeBytes:bytes.length,contentType:"application/gzip"},signature:{keyId,algorithm:"Ed25519",value:signature,signedPayloadSha256:manifestSha256,publicKey}};
const publish=await fetch(apiBase+"/api/internal/releases/publish",{method:"POST",headers:{"content-type":"application/json","x-mateo-release-token":publishToken},body:JSON.stringify(body)});if(!publish.ok)throw new Error("Mateo publish failed: "+await publish.text());console.log(await publish.text());