'use strict';
const fs=require('fs');const path=require('path');const axios=require('axios');const MateoUpdater=require('./MateoUpdater');const DEFAULT_BASE_URL='https://api.mateobot.vercel.app';
class MateoControlClient{
 constructor({config,logger,version='unknown',platform='messenger',rootDir=process.cwd()}={}){this.config=config;this.logger=logger;this.version=version;this.platform=platform;this.rootDir=rootDir;this.baseUrl=String(process.env.MATEO_API_BASE_URL||config?.get('mateo.apiBaseUrl',DEFAULT_BASE_URL)||DEFAULT_BASE_URL).replace(/\/+$/,'');this.apiVersion=String(process.env.MATEO_API_VERSION||config?.get('mateo.apiVersion','v1')||'v1');this.botKey=String(process.env.MATEO_BOT_KEY||'').trim();this.channel=String(process.env.MATEO_UPDATE_CHANNEL||config?.get('mateo.updateChannel','stable')||'stable');this.heartbeatIntervalMs=this._positiveInt(process.env.MATEO_HEARTBEAT_INTERVAL_MS||config?.get('mateo.heartbeatIntervalMs',300000),300000);this.updateCheckIntervalMs=this._positiveInt(process.env.MATEO_UPDATE_CHECK_INTERVAL_MS||config?.get('mateo.updateCheckIntervalMs',21600000),21600000);this.controlPollIntervalMs=this._positiveInt(process.env.MATEO_CONTROL_POLL_INTERVAL_MS||config?.get('mateo.controlPollIntervalMs',10000),10000);this.accessToken=null;this.expiresAt=null;this.installationId=String(process.env.MATEO_INSTALLATION_ID||'').trim()||null;this.authenticated=false;this.lastError=null;this.lastHeartbeatAt=null;this.lastUpdateCheckAt=null;this.lastAuthAt=null;this.latestRelease=null;this._heartbeatTimer=null;this._updateTimer=null;this._controlTimer=null;this._connecting=null;this.updater=new MateoUpdater({client:this,logger,rootDir,config})}
 _positiveInt(value,fallback){const n=Number(value);return Number.isSafeInteger(n)&&n>0?n:fallback}
 get enabled(){return Boolean(this.botKey)}
 _url(p){return this.baseUrl+'/api/fmb/'+this.apiVersion+p}
 _publicUrl(p){return this._url(p)}
 async _request(method,path,{data,params,auth=true,timeout=15000}={}){if(auth&&!this.accessToken)throw new Error('mateo_not_authenticated');try{const response=await axios.request({method,url:this._url(path),data,params,timeout,headers:auth?{Authorization:'Bearer '+this.accessToken}:undefined,validateStatus:()=>true});if(response.status<200||response.status>=300){const error=new Error('mateo_'+(response.data?.error||'http_'+response.status));error.status=response.status;throw error}return response.data}catch(error){this.lastError=error.message||String(error);throw error}}
 async _withReauth(fn){try{return await fn()}catch(error){if(error?.status===401&&this.enabled){this.accessToken=null;this.authenticated=false;await this.authenticate();return fn()}throw error}}
 async reportUpdateState(){try{const dir=path.join(this.rootDir,'data','.mateo-update');for(const file of ['success.json','rollback.json']){const p=path.join(dir,file);if(fs.existsSync(p)){const state=JSON.parse(fs.readFileSync(p,'utf8'));await this._withReauth(()=>this._request('POST','/updates/report',{data:{status:file==='success.json'?'success':'rollback',toVersion:state.version,details:{error:state.error||null}}}));fs.renameSync(p,p+'.reported')}}}catch(error){this.logger?.warn('[MATEO] Update state report failed: '+(error.message||error))}}
 async authenticate(){if(!this.enabled)return{enabled:false};if(this._connecting)return this._connecting;this._connecting=(async()=>{const challenge=await axios.post(this._url('/auth/challenge'),{},{timeout:15000,validateStatus:()=>true});if(challenge.status<200||challenge.status>=300)throw new Error('mateo_challenge_unavailable');const session=await axios.post(this._url('/auth/session'),{key:this.botKey,challengeId:challenge.data.id},{timeout:15000,validateStatus:()=>true});if(session.status<200||session.status>=300)throw new Error('mateo_authentication_failed');this.accessToken=session.data.accessToken;this.expiresAt=session.data.expiresAt||null;this.installationId=session.data.installationId||this.installationId;this.authenticated=true;this.lastAuthAt=new Date().toISOString();this.lastError=null;await this.reportUpdateState();this.logger?.info('[MATEO] Control plane authenticated. Installation: '+(this.installationId||'unknown'));return{enabled:true,installationId:this.installationId,apiVersion:session.data.apiVersion||this.apiVersion,expiresAt:this.expiresAt}})().finally(()=>{this._connecting=null});return this._connecting}
 async heartbeat(app){if(!this.enabled)return{enabled:false};if(!this.authenticated)await this.authenticate();const status=app?.status?.()||{},memory=process.memoryUsage(),updater=this.updater.status();const payload={botVersion:this.version,apiVersion:this.apiVersion,platform:process.platform+':'+this.platform,arch:process.arch,nodeVersion:process.version,runtime:'node',uptimeSeconds:Math.floor(process.uptime()),memoryUsedBytes:memory.rss,commandCount:Number.isSafeInteger(status.commands)?status.commands:null,capabilities:{...this._capabilities(),storage:status.storage?.mode||'unknown',database:status.storage?.mode||'unknown',adapter:status.platform?.adapter||'unknown'}};const result=await this._withReauth(()=>this._request('POST','/installation/heartbeat',{data:payload}));this.lastHeartbeatAt=new Date().toISOString();return result}
 async checkForUpdates(){if(!this.enabled)return{enabled:false};if(!this.authenticated)await this.authenticate();const result=await this._withReauth(()=>this._request('GET','/updates/check',{params:{channel:this.channel}}));this.lastUpdateCheckAt=new Date().toISOString();this.latestRelease=result.latest||null;return result}
 async updateNow(app){if(!this.enabled)return{enabled:false};if(!this.authenticated)await this.authenticate();return this.updater.check(app)}
 async _postActionResult(actionId,status,result={}){try{await this._withReauth(()=>this._request('POST','/control/actions/'+encodeURIComponent(actionId)+'/result',{data:{status,result}}))}catch(error){this.logger?.warn('[MATEO] Control action result failed: '+(error.message||error))}}
 async _diagnostics(){const status=this._safeDiagnostics(this.status());const appStatus=this._app?.status?.()||{};return{mateoVersion:this.version,node:process.version,os:process.platform,arch:process.arch,uptimeSeconds:Math.floor(process.uptime()),memory:{rss:process.memoryUsage().rss,heapUsed:process.memoryUsage().heapUsed},installationId:this.installationId,installationStatus:appStatus.status||'unknown',lastHeartbeatAt:this.lastHeartbeatAt,lastUpdateCheckAt:this.lastUpdateCheckAt,capabilities:this._capabilities(),adapter:appStatus.platform?.adapter||'unknown',database:appStatus.storage?.mode||'unknown',recentErrorCategories:[]}}
 _safeDiagnostics(value){return value}
 _capabilities(){return{controlPlane:true,heartbeat:true,updateCheck:true,signedManifests:this.updater.status().trustConfigured,rollback:true,commandRegistry:true,remoteManagement:true,diagnostics:true}}
 async _executeControlAction(action){const type=String(action?.action_type||'');if(!type)return{ok:false,error:'missing_action_type'};if(type==='diagnostics')return{ok:true,report:await this._diagnostics()};if(type==='start')return{ok:true,alreadyRunning:true};if(type==='stop'){await this._postActionResult(action.id,'succeeded',{accepted:true,operation:'stop'});await this._app?.shutdown('mateo-remote-stop').catch(()=>{});setTimeout(()=>process.exit(0),250);return{ok:true,stopping:true}}if(type==='restart'){await this._postActionResult(action.id,'succeeded',{accepted:true,operation:'restart'});const child=spawn(process.execPath,[path.join(this.rootDir,'index.js')],{cwd:this.rootDir,env:process.env,detached:true,stdio:'ignore'});child.unref();await this._app?.shutdown('mateo-remote-restart').catch(()=>{});setTimeout(()=>process.exit(0),250);return{ok:true,restarting:true}}if(type==='update'){const result=await this.updateNow(this._app);return{ok:Boolean(result?.ok),result}}if(type==='rollback'){const helper=path.join(this.rootDir,'scripts','mateo-update-helper.js');const child=spawn(process.execPath,[helper,'--rollback','--root',this.rootDir],{cwd:this.rootDir,detached:true,stdio:'ignore',windowsHide:true});child.unref();await this._app?.shutdown('mateo-remote-rollback').catch(()=>{});setTimeout(()=>process.exit(0),250);return{ok:true,rollingBack:true}}return{ok:false,error:'unsupported_action'}}
 async pollControlActions(app){if(!this.enabled||!this.authenticated)return{actions:[]};this._app=app;const result=await this._withReauth(()=>this._request('GET','/control/actions'));for(const action of result?.actions||[]){try{const execution=await this._executeControlAction(action);await this._postActionResult(action.id,execution.ok?'succeeded':'failed',execution.ok?execution.result||execution:{error:execution.error||'action_failed'})}catch(error){await this._postActionResult(action.id,'failed',{error:error.message||String(error)})}}return result}
 async features(){if(!this.enabled)return{enabled:false};if(!this.authenticated)await this.authenticate();return this._withReauth(()=>this._request('GET','/features'))}
 async support(){try{const response=await axios.get(this._publicUrl('/support'),{timeout:10000,validateStatus:()=>true});if(response.status<200||response.status>=300)throw new Error('mateo_support_unavailable');return response.data}catch(error){this.lastError=error.message||String(error);throw error}}
 start(app){this._app=app;if(!this.enabled){this.logger?.info('[MATEO] Control plane disabled; set MATEO_BOT_KEY to connect this installation.');return}this.stop();this.authenticate().then(()=>this.heartbeat(app)).then(()=>this.pollControlActions(app)).then(()=>this.checkForUpdates()).then(result=>{if(result?.available)this.logger?.info('[MATEO] Update available: '+String(result.latest?.version||'unknown'));return this.updateNow(app)}).catch(error=>this.logger?.warn('[MATEO] Initial control-plane sync failed: '+(error.message||error)));this._heartbeatTimer=setInterval(()=>this.heartbeat(app).catch(error=>this.logger?.warn('[MATEO] Heartbeat failed: '+(error.message||error))),this.heartbeatIntervalMs);this._controlTimer=setInterval(()=>this.pollControlActions(app).catch(error=>this.logger?.warn('[MATEO] Control poll failed: '+(error.message||error))),this.controlPollIntervalMs);this._updateTimer=setInterval(()=>this.checkForUpdates().then(result=>{if(result?.available)this.logger?.info('[MATEO] Update available: '+String(result.latest?.version||'unknown'));return this.updateNow(app)}).catch(error=>this.logger?.warn('[MATEO] Update sync failed: '+(error.message||error))),this.updateCheckIntervalMs);this._heartbeatTimer.unref?.();this._controlTimer.unref?.();this._updateTimer.unref?.()}
 async stop(){if(this._heartbeatTimer)clearInterval(this._heartbeatTimer);if(this._updateTimer)clearInterval(this._updateTimer);if(this._controlTimer)clearInterval(this._controlTimer);this._heartbeatTimer=null;this._updateTimer=null;this._controlTimer=null;this.accessToken=null;this.authenticated=false}
 status(){return{enabled:this.enabled,authenticated:this.authenticated,installationId:this.installationId,apiVersion:this.apiVersion,channel:this.channel,lastAuthAt:this.lastAuthAt,lastHeartbeatAt:this.lastHeartbeatAt,lastUpdateCheckAt:this.lastUpdateCheckAt,latestVersion:this.latestRelease?.version||null,lastError:this.lastError,offlineGraceHours:Number(process.env.MATEO_OFFLINE_GRACE_HOURS||this.config?.get('mateo.offlineGraceHours',168)),updater:this.updater.status()}}
}
module.exports=MateoControlClient;