'use strict';
const fs=require('fs');const path=require('path');const crypto=require('crypto');const {spawn,execFileSync}=require('child_process');const axios=require('axios');
class MateoUpdater{
 constructor({client,logger,rootDir=process.cwd(),config}={}){this.client=client;this.logger=logger;this.config=config;this.rootDir=rootDir;this.dir=path.join(rootDir,'data','.mateo-update');this.publicKey=process.env.MATEO_SIGNING_PUBLIC_KEY||config?.get('mateo.signingPublicKey','');this.auto=String(process.env.MATEO_AUTO_UPDATE||config?.get('mateo.autoUpdate',true)).toLowerCase()!=='false';this.last=null;this.busy=false}
 _safeVersion(v){if(!/^\d+\.\d+\.\d+(?:[-+][0-9A-Za-z.-]+)?$/.test(String(v||'')))throw new Error('invalid_release_version');return String(v)}
 async applyManifest(manifestResponse,app){if(this.busy)return{ok:false,reason:'update_in_progress'};this.busy=true;try{const release=manifestResponse.release||{},manifest=manifestResponse.manifest,artifact=manifestResponse.artifact,signature=manifestResponse.signature;if(!manifest||!artifact?.downloadUrl||!signature?.value)throw new Error('incomplete_release');const version=this._safeVersion(release.version||manifest.version);if(!this.publicKey)throw new Error('release_trust_root_not_configured');const canonical=JSON.stringify(manifest),manifestHash=crypto.createHash('sha256').update(canonical).digest('hex');if(manifestHash!==manifestResponse.manifestSha256)throw new Error('manifest_hash_mismatch');if(signature.signedPayloadSha256!==manifestHash)throw new Error('signature_payload_mismatch');const ok=crypto.verify(null,Buffer.from(canonical),crypto.createPublicKey(this.publicKey),Buffer.from(signature.value,'base64url'));if(!ok)throw new Error('manifest_signature_invalid');fs.mkdirSync(this.dir,{recursive:true});const archive=path.join(this.dir,version+'.tar.gz'),stage=path.join(this.dir,'staged',version);fs.rmSync(stage,{recursive:true,force:true});fs.mkdirSync(stage,{recursive:true});const response=await axios.get(artifact.downloadUrl,{responseType:'arraybuffer',timeout:120000,maxContentLength:Math.max(Number(artifact.sizeBytes||0)+10485760,1073741824),maxBodyLength:Math.max(Number(artifact.sizeBytes||0)+10485760,1073741824),validateStatus:s=>s>=200&&s<300});const bytes=Buffer.from(response.data);if(bytes.length!==Number(artifact.sizeBytes))throw new Error('artifact_size_mismatch');const hash=crypto.createHash('sha256').update(bytes).digest('hex');if(hash!==artifact.sha256)throw new Error('artifact_hash_mismatch');fs.writeFileSync(archive,bytes,{flag:'wx'});execFileSync('tar',['-xzf',archive,'-C',stage],{stdio:'ignore'});if(!fs.existsSync(path.join(stage,'index.js')))throw new Error('release_entrypoint_missing');if(app?.backup?.create)await app.backup.create('mateo-pre-update');const child=spawn(process.execPath,[path.join(this.rootDir,'scripts','mateo-update-helper.js'),'--pid',String(process.pid),'--root',this.rootDir,'--stage',stage,'--version',version],{cwd:this.rootDir,detached:true,stdio:'ignore',windowsHide:true});child.unref();this.last={version,status:'scheduled',at:new Date().toISOString()};this.logger?.warn('[MATEO] Verified update '+version+'; activation scheduled.');if(app){await app.shutdown('mateo-update').catch(()=>{});setTimeout(()=>process.exit(0),250)}return{ok:true,scheduled:true,version}}catch(error){this.last={status:'failed',error:error.message,at:new Date().toISOString()};this.logger?.warn('[MATEO] Update rejected: '+error.message);return{ok:false,error:error.message}}finally{this.busy=false}}
 async check(app){if(!this.auto)return{ok:false,reason:'auto_update_disabled'};const result=await this.client._request('GET','/updates/manifest',{params:{channel:this.client.channel}});if(!result?.updateAvailable)return{ok:true,available:false};return this.applyManifest(result,app)}
 status(){return{autoUpdate:this.auto,trustConfigured:Boolean(this.publicKey),last:this.last}}
}
module.exports=MateoUpdater;